image: gitpod/workspace-full
tasks:
  - name: install deps
    before: |
      brew install kubernetes-cli starship
      echo "eval $(starship init bash)" >> ~/.bashrc
      echo "eval $(starship init zsh)" >> ~/.zshrc
    command: zsh
    
vscode:
  extensions:
    - "golang.Go"
    - "ms-azuretools.vscode-docker"

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false